apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-test-pipeline
spec:
  params:
    - name: image
      type: string
      description: image URL to push
    - name: source_url
      type: string
      description: git URL to pull from
  workspaces:
    - name: source-workspace # Directory where application source is located. (REQUIRED)
    - name: cache-workspace # Directory where cache is stored (OPTIONAL)
  tasks:
    - name: fetch-repository # This task fetches a repository from github, using the `git-clone` task you installed
      taskRef:
        name: git-clone
      workspaces:
        - name: output 
          workspace: source-workspace
      params:
        - name: url
          value: "$(params.source_url)" 
        - name: deleteExisting
          value: true
    - name: kaniko-chains 
      taskRef:
        name: kaniko 
      runAfter:
        - fetch-repository 
      workspaces:
        - name: source
          workspace: source-workspace
      params:
        - name: IMAGE
          value: "$(params.image)"
    - name: display-results
      runAfter:
        - kaniko-chains
      taskSpec:
        steps:
          - name: print
            image: docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
            script: |
              #!/usr/bin/env bash
              set -e
              echo "Digest of created app image: $(params.DIGEST)"              
        params:
          - name: DIGEST
      params:
        - name: DIGEST
          value: $(tasks.kaniko-chains.results.IMAGE_DIGEST)